### PR TITLE
A bit of usage info

### PR DESCRIPTION
**Pull request by magnusviri**
For newbs like me.

### CODE REVIEW

**Comment by magnusviri** [comment]
I have no idea how this went to the wrong repo...

**Comment by magnusviri** [comment]
Ugh, I know how it went to the wrong repo. I forked pantry.zero for my pantry. Then I forked pantry.core to make the change, but pantry.core was forked from pantry.zero, so it just sent me to my fork, and I was too sleepy to notice. I know I can change the git fork source for my repo (I can't remember what it's called), but wouldn't doing that break the eventual decentralized look up?

**Comment by mxcl** [comment]
Forks of this repo will be part of the graph, if you want to contribute to pantry.core, you need to fork that.

You *can* have multiple forks of the same repo.

> but wouldn't doing that break the eventual decentralized look up?

should be fine. Either way we have to cater to what people have done! This may be the first edge case we code for.

**Comment by mxcl** [comment]
Closing, but this is welcome on `pantry.core`

**Pull request closed without merging**
